/*
 *    Copyright 2006-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.merge.xml;

import org.mybatis.generator.merge.MergeTestCase;

/**
 * This test is related to issue #87 where XML files are slightly different
 * after running through the XML merger.
 *
 * @author Jeff Butler
 */
public class IdenticalFilesShouldBeTheSameAfterMerge extends MergeTestCase {
    @Override
    public String existingContent(String parameter) {
        return """
               <?xml version="1.0" encoding="UTF-8"?>
               <!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "https://mybatis.org/dtd/mybatis-3-mapper.dtd">
               <mapper namespace="org.mybatis.test.TestMapper">
                   <insert id="insert" parameterType="org.mybatis.test.TestRecord">
                       <!--
                       WARNING - @mbg.generated
                       This element is automatically generated by MyBatis Generator, do not modify.
                       -->
                       insert into myschema.mytable (id, description)
                       values (#{id}, #{description})
                   </insert>
                   <select id="selectWithCdata1">
                       <!--
                       WARNING - @mbg.generated
                       This element is automatically generated by MyBatis Generator, do not modify.
                       -->
                       <![CDATA[
                           select foo from bar where foo < 22
                       ]]>
                   </select>
                   <select id="selectWithCdata2">
                       <!--
                       WARNING - @mbg.generated
                       This element is automatically generated by MyBatis Generator, do not modify.
                       -->
                       select foo from bar where foo <![CDATA[ < ]]> 22
                   </select>
               </mapper>""";
    }

    @Override
    public String newContent(String parameter) {
        return existingContent(parameter);
    }

    @Override
    public String expectedContentAfterMerge(String parameter) {
        return existingContent(parameter);
    }
}
