package propertyType.noLobs.modelDto;

import java.util.ArrayList;
import java.util.List;

public class UserPhotosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public UserPhotosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleIsNull() {
            addCriterion("PHOTO_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleIsNotNull() {
            addCriterion("PHOTO_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleEqualTo(String value) {
            addCriterion("PHOTO_TITLE =", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleNotEqualTo(String value) {
            addCriterion("PHOTO_TITLE <>", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleGreaterThan(String value) {
            addCriterion("PHOTO_TITLE >", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleGreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO_TITLE >=", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleLessThan(String value) {
            addCriterion("PHOTO_TITLE <", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleLessThanOrEqualTo(String value) {
            addCriterion("PHOTO_TITLE <=", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleLike(String value) {
            addCriterion("PHOTO_TITLE like", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleNotLike(String value) {
            addCriterion("PHOTO_TITLE not like", value, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleIn(List<String> values) {
            addCriterion("PHOTO_TITLE in", values, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleNotIn(List<String> values) {
            addCriterion("PHOTO_TITLE not in", values, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleBetween(String value1, String value2) {
            addCriterion("PHOTO_TITLE between", value1, value2, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTitleNotBetween(String value1, String value2) {
            addCriterion("PHOTO_TITLE not between", value1, value2, "photoTitle");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeIsNull() {
            addCriterion("PHOTO_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeIsNotNull() {
            addCriterion("PHOTO_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeEqualTo(String value) {
            addCriterion("PHOTO_TYPE =", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeNotEqualTo(String value) {
            addCriterion("PHOTO_TYPE <>", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeGreaterThan(String value) {
            addCriterion("PHOTO_TYPE >", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO_TYPE >=", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeLessThan(String value) {
            addCriterion("PHOTO_TYPE <", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeLessThanOrEqualTo(String value) {
            addCriterion("PHOTO_TYPE <=", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeLike(String value) {
            addCriterion("PHOTO_TYPE like", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeNotLike(String value) {
            addCriterion("PHOTO_TYPE not like", value, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeIn(List<String> values) {
            addCriterion("PHOTO_TYPE in", values, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeNotIn(List<String> values) {
            addCriterion("PHOTO_TYPE not in", values, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeBetween(String value1, String value2) {
            addCriterion("PHOTO_TYPE between", value1, value2, "photoType");
            return (Criteria) this;
        }

        public Criteria andPhotoTypeNotBetween(String value1, String value2) {
            addCriterion("PHOTO_TYPE not between", value1, value2, "photoType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USERPHOTOS
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 15 15:13:25 HST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}