/*
 *    Copyright 2006-2025 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 */
package org.mybatis.generator.eclipse.core.tests.merge;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mybatis.generator.eclipse.core.merge.EclipseDomUtils.getCompilationUnitFromSource;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.eclipse.jdt.core.dom.CompilationUnit;
import org.eclipse.jface.text.Document;
import org.eclipse.jface.text.IDocument;
import org.eclipse.text.edits.TextEdit;
import org.junit.jupiter.api.Test;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.eclipse.core.merge.ExistingJavaFileVisitor;

public class ExistingJavaFileVisitorTest {

    @Test
    public void testRegularClass() throws Exception {
        InputStream resource = getClass().getResourceAsStream("/org/mybatis/generator/eclipse/core/tests/merge/resources/AwfulTable.java.src");
        String source = getResourceAsString(resource);
        IDocument document = new Document(source);
        CompilationUnit cu = getCompilationUnitFromSource(source);
                
        cu.recordModifications();
        ExistingJavaFileVisitor visitor = new ExistingJavaFileVisitor(MergeConstants.getOldElementTags());
        
        // delete all the old generated stuff
        cu.accept(visitor);
        
        // generate a new compilation unit that is stripped of old stuff
        TextEdit textEdit = cu.rewrite(document, null);
        textEdit.apply(document);
        String result = document.get();

        assertThat(result).isEqualTo(
            """
            package org.mybatis.generator.eclipse.core.tests.merge.resources;

            import java.util.Arrays;

            public class AwfulTable extends AwfulTableKey {
            }
            """);
    }
    
    @Test
    public void testComplexClass() throws Exception {
        InputStream resource = getClass().getResourceAsStream("/org/mybatis/generator/eclipse/core/tests/merge/resources/AwfulTableExample.java.src");
        String source = getResourceAsString(resource);
        IDocument document = new Document(source);
        CompilationUnit cu = getCompilationUnitFromSource(source);
        cu.recordModifications();
        ExistingJavaFileVisitor visitor = new ExistingJavaFileVisitor(MergeConstants.getOldElementTags());
        
        // delete all the old generated stuff
        cu.accept(visitor);
        
        // generate a new compilation unit that is stripped of old stuff
        TextEdit textEdit = cu.rewrite(document, null);
        textEdit.apply(document);
        String result = document.get();

        assertThat(result).isEqualTo(
                """
                package org.mybatis.generator.eclipse.core.tests.merge.resources;

                import java.util.ArrayList;
                import java.util.List;

                public class AwfulTableExample {
                    /**
                     * This class was generated by MyBatis Generator.
                     * This class corresponds to the database table awful table
                     *
                     * @mbg.generated do_not_delete_during_merge Thu Aug 18 21:38:08 EDT 2016
                     */
                    public static class Criteria extends GeneratedCriteria {

                        protected Criteria() {
                            super();
                        }
                    }
                }
                """);
    }
    
    @Test
    public void testRegularInterface() throws Exception {
        InputStream resource = getClass().getResourceAsStream("/org/mybatis/generator/eclipse/core/tests/merge/resources/AwfulTableMapper.java.src");
        String source = getResourceAsString(resource);
        IDocument document = new Document(source);
        CompilationUnit cu = getCompilationUnitFromSource(source);
        cu.recordModifications();
        ExistingJavaFileVisitor visitor = new ExistingJavaFileVisitor(MergeConstants.getOldElementTags());
        
        // delete all the old generated stuff
        cu.accept(visitor);
        
        // generate a new compilation unit that is stripped of old stuff
        TextEdit textEdit = cu.rewrite(document, null);
        textEdit.apply(document);
        String result = document.get();

        assertThat(result).isEqualTo(
                """
                package org.mybatis.generator.eclipse.core.tests.merge.resources;

                import java.util.List;
                import mbg.test.mb3.generated.mixed.hierarchical.model.AwfulTable;
                import mbg.test.mb3.generated.mixed.hierarchical.model.AwfulTableExample;
                import mbg.test.mb3.generated.mixed.hierarchical.model.AwfulTableKey;
                import org.apache.ibatis.annotations.Delete;
                import org.apache.ibatis.annotations.Insert;
                import org.apache.ibatis.annotations.Param;
                import org.apache.ibatis.annotations.ResultMap;
                import org.apache.ibatis.annotations.Select;
                import org.apache.ibatis.annotations.SelectKey;
                import org.apache.ibatis.annotations.Update;

                public interface AwfulTableMapper {
                }
                """);
    }

    public static String getResourceAsString(InputStream resource) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(resource));
        StringBuilder sb = new StringBuilder();

        int c;
        while ((c = br.read()) != -1) {
            sb.append((char) c);
        }

        br.close();

        return sb.toString();
    }
}
