/*
 *    Copyright 2006-2025 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 */
package org.mybatis.generator.eclipse.core.tests.merge;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mybatis.generator.eclipse.core.tests.merge.support.TestResourceGenerator.simpleClassWithAllGeneratedItems;
import static org.mybatis.generator.eclipse.core.tests.merge.support.TestResourceGenerator.simpleClassWithGeneratedAndCustomItems;
import static org.mybatis.generator.eclipse.core.tests.merge.support.TestResourceGenerator.simpleInterfaceWithAllGeneratedItems;
import static org.mybatis.generator.eclipse.core.tests.merge.support.TestResourceGenerator.simpleInterfaceWithGeneratedAndCustomItems;

import org.junit.jupiter.api.Test;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.eclipse.core.merge.JavaFileMerger;

public class JavaFileMergerTest {

    @Test
    public void testMergeOnRegularClasses() throws Exception {
        String newJavaSource = simpleClassWithAllGeneratedItems();
        String existingJavaSource = simpleClassWithGeneratedAndCustomItems();
        JavaFileMerger merger = new JavaFileMerger(newJavaSource, existingJavaSource, MergeConstants.getOldElementTags());
        String mergedSource = merger.getMergedSource();
        
        mergedSource = mergedSource.replace("\t", "    ");
        
        assertThat(mergedSource).isEqualTo(
                """
                package org.mybatis.test;

                import java.math.BigDecimal;

                public class SimpleClass {
                    /**
                     * This field was generated by MyBatis Generator.
                     * @mbg.generated
                     */
                    private int id;

                    /**
                     * This method was generated by MyBatis Generator.
                     * @mbg.generated
                     */
                    public int getId() {
                        return id;
                    }

                    /**
                     * This method was generated by MyBatis Generator.
                     * @mbg.generated
                     */
                    public void setId(int id) {
                        this.id = id;
                    }

                    private BigDecimal amount;

                    public BigDecimal getAmount() {
                        return amount;
                    }

                    public void setAmount(BigDecimal amount) {
                        this.amount = amount;
                    }
                }""");
        
    }

    @Test
    public void testMergeOnRegularInterfaces() throws Exception {
        String newJavaSource = simpleInterfaceWithAllGeneratedItems();
        String existingJavaSource = simpleInterfaceWithGeneratedAndCustomItems();
        JavaFileMerger merger = new JavaFileMerger(newJavaSource, existingJavaSource, MergeConstants.getOldElementTags());
        String mergedSource = merger.getMergedSource();
        
        mergedSource = mergedSource.replace("\t", "    ");
        
        assertThat(mergedSource).isEqualTo(
                """
                package org.mybatis.test;

                public interface SimpleInterface {
                    /**
                     * This method was generated by MyBatis Generator.
                     * @mbg.generated
                     */
                    int count();

                    /**
                     * This method was generated by MyBatis Generator.
                     * @mbg.generated
                     */
                    @javax.annotation.Generated("org.mybatis.generator.api.MyBatisGenerator")
                    int add(int a, int b);

                    int nonGeneratedMethod();
                }""");
   }
}
