package fieldType.noLobs.modelDto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@XmlRootElement(name="Photos",namespace="http://mybatis.generator.org/plugins/jaxb/test")
@XmlAccessorType(XmlAccessType.FIELD)
public class UserPhotos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERPHOTOS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERPHOTOS.PHOTO_TITLE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    private String photoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERPHOTOS.PHOTO_TYPE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    private String photoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERPHOTOS.PHOTO
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    @XmlTransient
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERPHOTOS.USER_ID
     *
     * @return the value of USERPHOTOS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERPHOTOS.USER_ID
     *
     * @param userId the value for USERPHOTOS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERPHOTOS.PHOTO_TITLE
     *
     * @return the value of USERPHOTOS.PHOTO_TITLE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public String getPhotoTitle() {
        return photoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERPHOTOS.PHOTO_TITLE
     *
     * @param photoTitle the value for USERPHOTOS.PHOTO_TITLE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setPhotoTitle(String photoTitle) {
        this.photoTitle = photoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERPHOTOS.PHOTO_TYPE
     *
     * @return the value of USERPHOTOS.PHOTO_TYPE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public String getPhotoType() {
        return photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERPHOTOS.PHOTO_TYPE
     *
     * @param photoType the value for USERPHOTOS.PHOTO_TYPE
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setPhotoType(String photoType) {
        this.photoType = photoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERPHOTOS.PHOTO
     *
     * @return the value of USERPHOTOS.PHOTO
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERPHOTOS.PHOTO
     *
     * @param photo the value for USERPHOTOS.PHOTO
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public UserPhotos() {
        //Needed For JAXB serialization.
    }
}