/**
 *    Copyright 2006-2020 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.internal;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.comments.JavadocComment;
import com.github.javaparser.ast.type.PrimitiveType;
import com.github.javaparser.printer.PrettyPrinter;
import com.github.javaparser.printer.PrettyPrinterConfiguration;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;

import static com.github.javaparser.ast.Modifier.Keyword;
import static com.github.javaparser.ast.Modifier.createModifierList;

/**
 *
 * @author wang.jiyong
 */
public class JavaFileMergerTest {

    private final JavadocComment mbgGeneratedComment = new JavadocComment("@mbg.generated");

    @Test
    public void testThatFilesAreTheSameAfterMerge() throws Exception {
        JavaFileMerger javaFileMerger = new JavaFileMerger();
        String oldFile = createExistingFile();
        String newFile = createNewFile();
        String result = javaFileMerger.mergeJavaFile(newFile, new ByteArrayInputStream(oldFile.getBytes()), "Test", "UTF-8");
        assert result.equals(createExpectFile());
    }

    private String createExistingFile() {
        CompilationUnit existingUnit = new CompilationUnit();
        existingUnit.setPackageDeclaration("org.mybatis.generator");
        existingUnit.addImport("org.mybatis.t1");
        existingUnit.addImport("org.mybatis.t2");

        existingUnit.addClass("Test", Keyword.PUBLIC)
                .addMember(createFieldMember("id", true))
                .addMember(createFieldMember("extraField", false))
                .addMember(createMethodMember("insert", true))
                .addMember(createMethodMember("select", false))
                .addMember(createClassMember("Criteria", true))
                .addMember(createClassMember("MyInnerClass", false));

        assert existingUnit.getClassByName("Test").isPresent();
        ClassOrInterfaceDeclaration publicClass = existingUnit.getClassByName("Test").get();
        publicClass.addAnnotation("Mapper");
        publicClass.addAnnotation("CustomAnnotation");

        return prettyPrinter(existingUnit);
    }


    private String createNewFile() {
        CompilationUnit existingUnit = new CompilationUnit();
        existingUnit.setPackageDeclaration("org.mybatis.generator");
        //new import
        existingUnit.addImport("java.util.Date");
        existingUnit.addImport("java.util.HashMap");

        existingUnit.addClass("Test", Keyword.PUBLIC)
                .addMember(createFieldMember("autoGeneratedField", true))
                .addMember(createMethodMember("autoGeneratedMethod", true))
                .addMember(createClassMember("AutoGeneratedClass", true));
        assert existingUnit.getClassByName("Test").isPresent();
        ClassOrInterfaceDeclaration publicClass = existingUnit.getClassByName("Test").get();
        publicClass.addAnnotation("Mapper");
        publicClass.addAnnotation("Component");
        return prettyPrinter(existingUnit);
    }


    private String createExpectFile() {
        CompilationUnit existingUnit = new CompilationUnit();
        existingUnit.setPackageDeclaration("org.mybatis.generator");
        existingUnit.addImport("org.mybatis.t1");
        existingUnit.addImport("org.mybatis.t2");
        existingUnit.addImport("java.util.Date");
        existingUnit.addImport("java.util.HashMap");

        existingUnit.addClass("Test", Keyword.PUBLIC)
                .addMember(createFieldMember("autoGeneratedField", true))
                .addMember(createFieldMember("extraField", false))
                .addMember(createMethodMember("autoGeneratedMethod", true))
                .addMember(createMethodMember("select", false))
                .addMember(createClassMember("AutoGeneratedClass", true))
                .addMember(createClassMember("MyInnerClass", false));
        assert existingUnit.getClassByName("Test").isPresent();
        ClassOrInterfaceDeclaration publicClass = existingUnit.getClassByName("Test").get();
        publicClass.addAnnotation("Mapper");
        publicClass.addAnnotation("CustomAnnotation");
        publicClass.addAnnotation("Component");
        return prettyPrinter(existingUnit);
    }

    public MethodDeclaration createMethodMember(String name, boolean isGenerated) {
        MethodDeclaration generatedMethod = new MethodDeclaration(createModifierList(Keyword.PUBLIC, Keyword.ABSTRACT), PrimitiveType.intType(), name);
        if (isGenerated) {
            generatedMethod.setComment(mbgGeneratedComment);
        }
        generatedMethod.setBody(null);
        return generatedMethod;
    }

    public FieldDeclaration createFieldMember(String name, boolean isGenerated) {
        FieldDeclaration extraField = new FieldDeclaration(createModifierList(Keyword.PRIVATE), PrimitiveType.longType().toBoxedType(), name);
        if (isGenerated) {
            extraField.setComment(mbgGeneratedComment);
        }
        return extraField;
    }

    public ClassOrInterfaceDeclaration createClassMember(String name, boolean isGenerated) {
        ClassOrInterfaceDeclaration extraInnerClass = new ClassOrInterfaceDeclaration(createModifierList(Keyword.PUBLIC, Keyword.STATIC),
                false, name);
        if (isGenerated) {
            extraInnerClass.setComment(mbgGeneratedComment);
        }
        return extraInnerClass;
    }

    public String prettyPrinter(CompilationUnit unit) {
        PrettyPrinterConfiguration conf = new PrettyPrinterConfiguration();
        PrettyPrinter prettyPrinter = new PrettyPrinter(conf);
        return prettyPrinter.print(unit);
    }
}
