package fieldType.noLobs.clientDao;

import fieldType.noLobs.modelDto.UserPhotos;
import fieldType.noLobs.modelDto.UserPhotosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int countByExample(UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int deleteByExample(UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insert(UserPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insertSelective(UserPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    List<UserPhotos> selectByExampleWithBLOBs(UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    List<UserPhotos> selectByExample(UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExampleSelective(@Param("record") UserPhotos record, @Param("example") UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") UserPhotos record, @Param("example") UserPhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERPHOTOS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExample(@Param("record") UserPhotos record, @Param("example") UserPhotosExample example);
}