package fieldType.noLobs.clientDao;

import fieldType.noLobs.modelDto.UsersToSkillsExample;
import fieldType.noLobs.modelDto.UsersToSkillsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersToSkillsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int countByExample(UsersToSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int deleteByExample(UsersToSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int deleteByPrimaryKey(UsersToSkillsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insert(UsersToSkillsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insertSelective(UsersToSkillsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    List<UsersToSkillsKey> selectByExample(UsersToSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExampleSelective(@Param("record") UsersToSkillsKey record, @Param("example") UsersToSkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExample(@Param("record") UsersToSkillsKey record, @Param("example") UsersToSkillsExample example);
}