package fieldType.withLobs.modelDto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="usersToSkillsKey")
public class UsersToSkillsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERSTOSKILLS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERSTOSKILLS.SKILL_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    private Short skillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERSTOSKILLS.USER_ID
     *
     * @return the value of USERSTOSKILLS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERSTOSKILLS.USER_ID
     *
     * @param userId the value for USERSTOSKILLS.USER_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERSTOSKILLS.SKILL_ID
     *
     * @return the value of USERSTOSKILLS.SKILL_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public Short getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERSTOSKILLS.SKILL_ID
     *
     * @param skillId the value for USERSTOSKILLS.SKILL_ID
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERSTOSKILLS
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    public UsersToSkillsKey() {
        //Needed For JAXB serialization.
    }
}