/*
 *    Copyright 2006-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.merge.java;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Stream;

import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.EnumConstantDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;

/**
 * Inspect a TypeDeclaration looking for members that should be merged. We only look for immediate children of the
 * TypeDeclaration, we do not recurse into nested types. There are three resulting lists of members:
 *
 * <ol>
 *     <li>customBodyMembers: members that should be merged with the target file because they are not generated by
 *     MyBatis Generator</li>
 *     <li>doNotDeleteBodyMembers: members that were originally generated by MyBatis Generator, but marked
 *     "do_not_delete_during_merge". This means that any matching member in the newly generated file should be removed,
 *     and these members should be merged. Currently, the only known use of this feature is the legacy Example classes.
 *     Those classes have a "Criteria" inner class that can be modified as an extension point.</li>
 *     <li>customEnumConstants: enum constants that should be merged with the target file because they are not
 *     generated by MyBatis Generator</li>
 * </ol>
 *
 * <p>If all lists are empty, there is no need to merge any members into a new file, and the new file can be used as is.
 */
public class CustomMemberGatherer {
    private final List<BodyDeclaration<?>> customBodyMembers = new ArrayList<>();
    private final List<BodyDeclaration<?>> doNotDeleteBodyMembers = new ArrayList<>();
    private final List<EnumConstantDeclaration> customEnumConstants = new ArrayList<>();

    public CustomMemberGatherer(TypeDeclaration<?> typeDeclaration) {
        typeDeclaration.getMembers().forEach(this::gatherCustomBodyMemberIfNeeded);

        if (typeDeclaration.isEnumDeclaration()) {
            typeDeclaration.asEnumDeclaration().getEntries().forEach(this::gatherCustomEnumConstantIfNeeded);
        }
    }

    public boolean hasAnyMembersToMerge() {
        return !customBodyMembers.isEmpty() || !doNotDeleteBodyMembers.isEmpty() || !customEnumConstants.isEmpty();
    }

    public Stream<BodyDeclaration<?>> allCustomBodyMembers() {
        return Stream.of(customBodyMembers.stream(), doNotDeleteBodyMembers.stream())
                .flatMap(Function.identity());
    }

    public Stream<BodyDeclaration<?>> doNotDeleteBodyMembers() {
        return doNotDeleteBodyMembers.stream();
    }

    public Stream<EnumConstantDeclaration> customEnumConstants() {
        return customEnumConstants.stream();
    }

    private void gatherCustomBodyMemberIfNeeded(BodyDeclaration<?> member) {
        // Generated annotation:
        //  - Generated Keep - add to do not delete list
        //  - Generated remove - return
        //  - Not Generated - check for old Javadoc comments

        GeneratedType generatedType = JavaMergeUtilities.checkForGeneratedAnnotation(member);
        if (generatedType == GeneratedType.GENERATED_KEEP) {
            doNotDeleteBodyMembers.add(member);
            return;
        } else if (generatedType == GeneratedType.GENERATED_REMOVE) {
            return;
        }

        generatedType = JavaMergeUtilities.checkForGeneratedJavadocTag(member);
        if (generatedType == GeneratedType.NOT_GENERATED) {
            customBodyMembers.add(member);
        } else if (generatedType == GeneratedType.GENERATED_KEEP) {
            doNotDeleteBodyMembers.add(member);
        }
    }

    private void gatherCustomEnumConstantIfNeeded(EnumConstantDeclaration member) {
        GeneratedType generatedType = JavaMergeUtilities.checkForGeneratedAnnotation(member);
        if (generatedType == GeneratedType.GENERATED_KEEP) {
            customEnumConstants.add(member);
            return;
        } else if (generatedType == GeneratedType.GENERATED_REMOVE) {
            return;
        }

        generatedType = JavaMergeUtilities.checkForGeneratedJavadocTag(member);
        if (generatedType == GeneratedType.NOT_GENERATED || generatedType == GeneratedType.GENERATED_KEEP) {
            customEnumConstants.add(member);
        }
    }
}
