/*
 *    Copyright 2006-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.merge.java;

import java.util.ArrayList;
import java.util.List;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.EnumConstantDeclaration;
import com.github.javaparser.printer.Printer;
import org.mybatis.generator.exception.MergeException;

/**
 * This class handles the task of merging changes into an existing Java file using JavaParser.
 * It supports merging by removing methods and fields that have specific Javadoc tags or annotations.
 *
 * <p>Given an existing source file and a newly generated file of the same name, the merger will:
 * <ol>
 *     <li>Parse the existing file looking for custom additions. A custom addition is defined in these ways:
 *         <ul>
 *             <li>A body element (field, method, nested class, etc.) not marked as generated - missing both a
 *                 <code>@Generated</code> annotation and an older style custom Javadoc tag.</li>
 *             <li>A body element (field, method, nested class, etc.) marked as generated by an older style custom
 *                 Javadoc tag and also containing the phrase "do_not_delete_during_merge".</li>
 *             <li>Any import in the existing file that is not present in the newly generated file</li>
 *             <li>Any super interface in the existing file that is not present in the newly generated file</li>
 *             <li>Any enum constant missing a "generated" marker in the existing file that is not present in the new
 *                 file</li>
 *         </ul>
 *         It is important to know that the parser will only look for direct children of either the public type or the
 *         first non-public type in a source file.
 *     </li>
 *     <li>If there are no custom additions, the newly generated file is returned unmodified.</li>
 *     <li>If there are custom additions, then:
 *         <ul>
 *             <li>Add any imports present in the existing file but missing in the new file</li>
 *             <li>Remove any members in the new file that match custom additions in the existing file</li>
 *             <li>Add all custom additions from the existing file</li>
 *             <li>The merged file is formatted and returned.</li>
 *         </ul>
 *     </li>
 * </ol>
 *
 * <p>This implementation differs from the original Eclipse-based implementation in the following ways:</p>
 * <ol>
 *     <li>This implementation supports merging enums and records</li>
 *     <li>Record merging will only merge custom and generated members. The record parameter list is always replaced
 *         with the newly generated record parameter list.
 *     </li>
 *     <li>This implementation does not support merging the super class from a newly generated file to an existing file.
 *     </li>
 *     <li>This implementation does not attempt to preserve custom annotations added to generated elements. With the
 *         generator now generating code with many annotations, it is challenging to distinguish between annotations
 *         created by MBG, and custom annotations added after code generation by a user. If you need to add
 *         annotations to generated elements, consider implementing a plugin that will create the annotations whenever
 *         the generator runs.
 *     </li>
 * </ol>
 *
 * @author Jeff Butler
 */
public class MergeIntoExistingJavaFileMerger implements JavaFileMerger {
    private final Printer printer;
    private final boolean isLexicalPreserving;

    public MergeIntoExistingJavaFileMerger(Printer printer, boolean isLexicalPreserving) {
        this.printer = printer;
        this.isLexicalPreserving = isLexicalPreserving;
    }

    /**
     * Merge a newly generated Java file with existing Java file content.
     *
     * @param newFileContent the content of the newly generated Java file
     * @param existingFileContent the content of the existing Java file
     * @return the merged source, properly formatted
     * @throws MergeException if the file cannot be merged for some reason
     */
    @Override
    public String getMergedSource(String newFileContent, String existingFileContent) throws MergeException {
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_25);
        if (isLexicalPreserving) {
            parserConfiguration.setLexicalPreservationEnabled(true);
        }

        JavaParser javaParser = new JavaParser(parserConfiguration);

        ParseResults existingFileParseResults = JavaMergeUtilities.parseAndFindMainTypeDeclaration(javaParser,
                existingFileContent, MergeFileType.EXISTING_FILE);

        // Gather custom members from the existing file. If none, just return the new file as is
        CustomMemberGatherer customMemberGatherer =
                new CustomMemberGatherer(existingFileParseResults.typeDeclaration());
        if (!customMemberGatherer.hasAnyMembersToMerge()) {
            return newFileContent;
        }

        // remove generated elements from the existing file
        List<BodyDeclaration<?>> membersToDelete = new ArrayList<>();
        existingFileParseResults.typeDeclaration().getMembers().forEach(member -> {
            GeneratedType generatedType = JavaMergeUtilities.checkForGeneratedAnnotation(member);
            if (generatedType == GeneratedType.GENERATED_REMOVE) {
                membersToDelete.add(member);
            }
            generatedType = JavaMergeUtilities.checkForGeneratedJavadocTag(member);
            if (generatedType == GeneratedType.GENERATED_REMOVE) {
                membersToDelete.add(member);
            }
        });
        for (BodyDeclaration<?> member : membersToDelete) {
            existingFileParseResults.typeDeclaration().remove(member);
        }

        // Remove generated enum constants
        if (existingFileParseResults.typeDeclaration().isEnumDeclaration()) {
            List<EnumConstantDeclaration> enumConstantsToDelete = new ArrayList<>();
            existingFileParseResults.typeDeclaration().asEnumDeclaration().getEntries().forEach(enumDec -> {
                GeneratedType generatedType = JavaMergeUtilities.checkForGeneratedAnnotation(enumDec);
                if (generatedType == GeneratedType.GENERATED_REMOVE) {
                    enumConstantsToDelete.add(enumDec);
                }
                generatedType = JavaMergeUtilities.checkForGeneratedJavadocTag(enumDec);
                if (generatedType == GeneratedType.GENERATED_REMOVE) {
                    enumConstantsToDelete.add(enumDec);
                }
            });
            for (EnumConstantDeclaration member : enumConstantsToDelete) {
                existingFileParseResults.typeDeclaration().asEnumDeclaration().remove(member);
            }
        }

        // 2. Parse the new file, gather generated elements and add to the existing file
        ParseResults newFileParseResults = JavaMergeUtilities.parseAndFindMainTypeDeclaration(javaParser,
                newFileContent, MergeFileType.NEW_FILE);

        // delete any members in the new file that match the old file members (this gets rid of new
        // do not delete members)
        for (BodyDeclaration<?> member : existingFileParseResults.typeDeclaration().getMembers()) {
            JavaMergeUtilities.deleteDuplicateMemberIfExists(newFileParseResults.typeDeclaration(), member);
        }

        // add members from the new file to the existing file
        for (BodyDeclaration<?> member : newFileParseResults.typeDeclaration().getMembers()) {
            existingFileParseResults.typeDeclaration().addMember(member);
        }

        // add any enum constants from the new file to the existing file
        if (newFileParseResults.typeDeclaration().isEnumDeclaration()) {
            existingFileParseResults.typeDeclaration().asEnumDeclaration().getEntries().addAll(
                    newFileParseResults.typeDeclaration().asEnumDeclaration().getEntries());
        }

        // 3. Add imports to existing file from new file that are not in existing file
        JavaMergeUtilities
                .findCustomImports(newFileParseResults.compilationUnit(), existingFileParseResults.compilationUnit())
                .forEach(existingFileParseResults.compilationUnit()::addImport);

        // Look for super interfaces in the new file and merge into the existing file if they aren't present
        JavaMergeUtilities.findCustomSuperInterfaces(newFileParseResults.typeDeclaration(),
                        existingFileParseResults.typeDeclaration())
                .forEach(t -> JavaMergeUtilities.addSuperInterface(existingFileParseResults.typeDeclaration(), t));

        // merge records
        // TODO(?) this is not really a merge so much as a replace - should we do a merge?
        if (existingFileParseResults.typeDeclaration().isRecordDeclaration()
                && newFileParseResults.typeDeclaration().isRecordDeclaration()) {
            // remove all record fields from the existing file and add from the new file
            existingFileParseResults.typeDeclaration().asRecordDeclaration().getParameters().clear();
            existingFileParseResults.typeDeclaration().asRecordDeclaration().getParameters().addAll(
                    newFileParseResults.typeDeclaration().asRecordDeclaration().getParameters());
        }

        // Return the new (merged) file
        return printer.print(existingFileParseResults.compilationUnit());
    }
}
