/*
 *    Copyright 2006-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.merge.java;

import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.printer.Printer;

/**
 * This class handles the task of merging changes into a new Java file using JavaParser.
 * It supports merging by removing methods and fields that have specific Javadoc tags or annotations.
 *
 * <p>Given an existing source file and a newly generated file of the same name, the merger will:
 * <ol>
 *     <li>Parse the existing file looking for custom additions. A custom addition is defined in these ways:
 *         <ul>
 *             <li>A body element (field, method, nested class, etc.) not marked as generated - missing both a
 *                 <code>@Generated</code> annotation and an older style custom Javadoc tag.</li>
 *             <li>A body element (field, method, nested class, etc.) marked as generated by an older style custom
 *                 Javadoc tag and also containing the phrase "do_not_delete_during_merge".</li>
 *             <li>Any import in the existing file that is not present in the newly generated file</li>
 *             <li>Any super interface in the existing file that is not present in the newly generated file</li>
 *             <li>Any enum constant missing a "generated" marker in the existing file that is not present in the new
 *                 file</li>
 *         </ul>
 *         It is important to know that the parser will only look for direct children of either the public type or the
 *         first non-public type in a source file.
 *     </li>
 *     <li>If there are no custom additions, the newly generated file is returned unmodified.</li>
 *     <li>If there are custom additions, then:
 *         <ul>
 *             <li>Add any imports present in the existing file but missing in the new file</li>
 *             <li>Remove any members in the new file that match custom additions in the existing file</li>
 *             <li>Add all custom additions from the existing file</li>
 *             <li>The merged file is formatted and returned.</li>
 *         </ul>
 *     </li>
 * </ol>
 *
 * <p>This implementation differs from the original Eclipse-based implementation in the following ways:</p>
 * <ol>
 *     <li>This implementation supports merging enums and records</li>
 *     <li>This implementation supports merging when the existing file is a class or interface, and the newly generated
 *         file is a record (the result will be a record).
 *     </li>
 *     <li>This implementation does not support merging the super class from an existing file to the newly generated
 *         file.</li>
 *     <li>This implementation does not attempt to preserve custom annotations added to generated elements. With the
 *         generator now generating code with many annotations, it is challenging to distinguish between annotations
 *         created by MBG, and custom annotations added after code generation by a user. If you need to add
 *         annotations to generated elements, consider implementing a plugin that will create the annotations whenever
 *         the generator runs.
 *     </li>
 * </ol>
 *
 * @author Freeman (original)
 * @author Jeff Butler (refactoring and enhancements)
 */
public class MergeIntoNewJavaFileMerger extends AbstractJavaMerger {

    public MergeIntoNewJavaFileMerger(Printer printer, boolean isLexicalPreserving) {
        super(printer, isLexicalPreserving);
    }

    @Override
    public String performMerge(CustomMemberGatherer customMemberGatherer, ParseResults existingFileParseResults,
                               ParseResults newFileParseResults) {
        TypeDeclaration<?> existingType = existingFileParseResults.typeDeclaration();
        TypeDeclaration<?> newType = newFileParseResults.typeDeclaration();

        // Delete elements in the new file that match doNotDeleteMembers from the existing file
        customMemberGatherer.doNotDeleteBodyMembers()
                .forEach(m -> JavaMergeUtilities.deleteDuplicateMemberIfExists(newType, m));

        // Look for custom imports in the existing file and merge into the new file
        JavaMergeUtilities
                .findCustomImports(existingFileParseResults.compilationUnit(), newFileParseResults.compilationUnit())
                .forEach(newFileParseResults.compilationUnit()::addImport);

        // Add custom body members from the existing file to the new file
        customMemberGatherer.allCustomBodyMembers().forEach(newType::addMember);

        // Add custom enum constants from the existing file to the new file
        if (newType.isEnumDeclaration()) {
            customMemberGatherer.customEnumConstants().forEach(newType.asEnumDeclaration()::addEntry);
        }

        // Look for custom super interfaces in the existing file and merge into the new file
        JavaMergeUtilities.findCustomSuperInterfaces(existingType, newType)
                .forEach(t -> JavaMergeUtilities.addSuperInterface(newType, t));

        // Return the new (merged) file
        return printer.print(newFileParseResults.compilationUnit());
    }
}
