/*
 *    Copyright 2006-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.merge.java;

import com.github.javaparser.ast.body.BodyDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.printer.Printer;

/**
 * This class handles the task of merging changes into an existing Java file using JavaParser.
 * It supports merging by removing methods and fields that have specific Javadoc tags or annotations.
 *
 * <p>Given an existing source file and a newly generated file of the same name, the merger will:
 * <ol>
 *     <li>Parse the existing file looking for custom additions. A custom addition is defined in these ways:
 *         <ul>
 *             <li>A body element (field, method, nested class, etc.) not marked as generated - missing both a
 *                 <code>@Generated</code> annotation and an older style custom Javadoc tag.</li>
 *             <li>A body element (field, method, nested class, etc.) marked as generated by an older style custom
 *                 Javadoc tag and also containing the phrase "do_not_delete_during_merge".</li>
 *             <li>Any import in the existing file that is not present in the newly generated file</li>
 *             <li>Any super interface in the existing file that is not present in the newly generated file</li>
 *             <li>Any enum constant missing a "generated" marker in the existing file that is not present in the new
 *                 file</li>
 *         </ul>
 *         It is important to know that the parser will only look for direct children of either the public type or the
 *         first non-public type in a source file.
 *     </li>
 *     <li>If there are no custom additions, the newly generated file is returned unmodified.</li>
 *     <li>If there are custom additions, then:
 *         <ul>
 *             <li>Add any imports present in the existing file but missing in the new file</li>
 *             <li>Remove any members in the new file that match custom additions in the existing file</li>
 *             <li>Add all custom additions from the existing file</li>
 *             <li>The merged file is formatted and returned.</li>
 *         </ul>
 *     </li>
 * </ol>
 *
 * <p>This implementation differs from the original Eclipse-based implementation in the following ways:</p>
 * <ol>
 *     <li>This implementation supports merging enums and records</li>
 *     <li>Record merging will only merge custom and generated members. The record parameter list is always replaced
 *         with the newly generated record parameter list.
 *     </li>
 *     <li>This implementation does not support merging the super class from a newly generated file to an existing file.
 *     </li>
 *     <li>This implementation does not attempt to preserve custom annotations added to generated elements. With the
 *         generator now generating code with many annotations, it is challenging to distinguish between annotations
 *         created by MBG, and custom annotations added after code generation by a user. If you need to add
 *         annotations to generated elements, consider implementing a plugin that will create the annotations whenever
 *         the generator runs.
 *     </li>
 * </ol>
 *
 * @author Jeff Butler
 */
public class MergeIntoExistingJavaFileMerger extends AbstractJavaMerger {
    public MergeIntoExistingJavaFileMerger(Printer printer, boolean isLexicalPreserving) {
        super(printer, isLexicalPreserving);
    }

    @Override
    public String performMerge(CustomMemberGatherer customMemberGatherer, ParseResults existingFileParseResults,
                               ParseResults newFileParseResults) {
        TypeDeclaration<?> existingType = existingFileParseResults.typeDeclaration();
        TypeDeclaration<?> newType = newFileParseResults.typeDeclaration();

        // remove generated elements from the existing file
        existingType.getMembers().stream()
                .filter(this::shouldDelete)
                .toList() // this avoids a concurrent modification problem
                .forEach(existingType::remove);

        // Remove generated enum constants
        if (existingType.isEnumDeclaration()) {
            existingType.asEnumDeclaration().getEntries().stream()
                    .filter(this::shouldDelete)
                    .toList() // this avoids a concurrent modification problem
                    .forEach(existingType::remove);
        }

        // delete any members in the new file that match the old file members (this gets rid of new
        // do not delete members)
        for (BodyDeclaration<?> member : existingType.getMembers()) {
            JavaMergeUtilities.deleteDuplicateMemberIfExists(newType, member);
        }

        // add members from the new file to the existing file
        for (BodyDeclaration<?> member : newType.getMembers()) {
            existingType.addMember(member);
        }

        // add any enum constants from the new file to the existing file
        if (newType.isEnumDeclaration() && existingType.isEnumDeclaration()) {
            existingType.asEnumDeclaration().getEntries().addAll(
                    newType.asEnumDeclaration().getEntries());
        }

        // 3. Add imports to existing file from new file that are not in existing file
        JavaMergeUtilities
                .copyMissingImports(newFileParseResults.compilationUnit(), existingFileParseResults.compilationUnit());

        // Look for super interfaces in the new file and merge into the existing file if they aren't present
        JavaMergeUtilities.copyMissingSuperInterfaces(newType, existingType);

        // merge records - this is not really a merge so much as a replacement. We would need to add the @Generated
        // annotation to record fields to perform a merge, which seems excessive.
        if (existingType.isRecordDeclaration() && newType.isRecordDeclaration()) {
            // remove all record fields from the existing file and add from the new file
            existingType.asRecordDeclaration().getParameters().clear();
            existingType.asRecordDeclaration().getParameters()
                    .addAll(newType.asRecordDeclaration().getParameters());
        }

        // Return the new (merged) file
        return printer.print(existingFileParseResults.compilationUnit());
    }

    private boolean shouldDelete(BodyDeclaration<?> bodyDeclaration) {
        GeneratedType generatedType = JavaMergeUtilities.checkForGeneratedAnnotation(bodyDeclaration);
        if (generatedType == GeneratedType.GENERATED_REMOVE) {
            return true;
        }
        generatedType = JavaMergeUtilities.checkForGeneratedJavadocTag(bodyDeclaration);
        return generatedType == GeneratedType.GENERATED_REMOVE;
    }
}
