package propertyType.noLobs.clientDao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import propertyType.noLobs.modelDto.UserBlog;
import propertyType.noLobs.modelDto.UserBlogExample;

public interface UserBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int countByExample(UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int deleteByExample(UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insert(UserBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int insertSelective(UserBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    List<UserBlog> selectByExampleWithBLOBs(UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    List<UserBlog> selectByExample(UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExampleSelective(@Param("record") UserBlog record, @Param("example") UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") UserBlog record, @Param("example") UserBlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERBLOG
     *
     * @mbggenerated Sun Sep 15 15:13:25 HST 2013
     */
    int updateByExample(@Param("record") UserBlog record, @Param("example") UserBlogExample example);
}