/*
 *    Copyright 2006-2025 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.mybatis.generator.plugins;

import java.util.ArrayList;
import java.util.List;

import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.JavaVisibility;

/**
 * This plugin generates custom mapper interfaces that extend the original generated mappers.
 *
 * <p>The plugin creates "Customer" prefixed mapper interfaces in a separate package
 * to allow for custom queries while maintaining separation from generated code.
 *
 * @author Goody
 */
public class CustomerMapperPlugin extends PluginAdapter {

    private static final String CUSTOMER_PREFIX = "Customer";
    private static final String CUSTOMER_PACKAGE = "customer";

    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    @Override
    public List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable) {
        List<GeneratedJavaFile> answer = new ArrayList<>();

        // Generate Customer Mapper interface
        Interface customerMapperInterface = generateCustomerMapperInterface(introspectedTable);
        GeneratedJavaFile customerMapperJavaFile = new GeneratedJavaFile(customerMapperInterface,
                context.getJavaClientGeneratorConfiguration().getTargetProject(),
                context.getProperty("javaFileEncoding"),
                context.getJavaFormatter());

        answer.add(customerMapperJavaFile);

        return answer;
    }

    private Interface generateCustomerMapperInterface(IntrospectedTable introspectedTable) {
        // Get original mapper info
        String originalMapperType = introspectedTable.getMyBatis3JavaMapperType();
        String originalMapperPackage = originalMapperType.substring(0, originalMapperType.lastIndexOf('.'));
        String originalMapperClassName = originalMapperType.substring(originalMapperType.lastIndexOf('.') + 1);

        // Remove "Mapper" suffix and add "Customer" prefix
        String entityName = originalMapperClassName.replace("Mapper", "");
        String customerMapperClassName = CUSTOMER_PREFIX + entityName + "Mapper";

        // Generate customer mapper package
        String customerMapperPackage = originalMapperPackage.replace(".dao", ".dao." + CUSTOMER_PACKAGE);
        String customerMapperFullType = customerMapperPackage + "." + customerMapperClassName;

        // Create customer mapper interface
        FullyQualifiedJavaType customerMapperType = new FullyQualifiedJavaType(customerMapperFullType);
        Interface customerMapperInterface = new Interface(customerMapperType);

        // Set interface properties
        customerMapperInterface.setVisibility(JavaVisibility.PUBLIC);

        // Add imports
        FullyQualifiedJavaType mapperAnnotationType = new FullyQualifiedJavaType("org.apache.ibatis.annotations.Mapper");
        customerMapperInterface.addImportedType(mapperAnnotationType);

        // Add @Mapper annotation
        customerMapperInterface.addAnnotation("@Mapper");

        // Add interface comment
        customerMapperInterface.addJavaDocLine("/**");
        customerMapperInterface.addJavaDocLine(" * Customer Mapper for " + entityName);
        customerMapperInterface.addJavaDocLine(" * Add custom queries here");
        customerMapperInterface.addJavaDocLine(" * Generated by MyBatis Generator Customer Mapper Plugin");
        customerMapperInterface.addJavaDocLine(" */");

        return customerMapperInterface;
    }
}